### PR TITLE
Allow flashing non-Dasharo EC firmware and fix edge case key detection

### LINKED ISSUE #1628: Can't flash original EC firmware with `dasharo_ectool`
### Component

Dasharo Tools Suite, other

### Device

NovaCustom NS5x 12th Gen, NovaCustom V54 14th Gen

### Dasharo version

1.7.2 (NS5x)/1.0.0 (MTL)

### Dasharo Tools Suite version

2.7.0

### Test case ID

_No response_

### Brief summary

`dasharo_ectool` can't flash original EC firmware

### How reproducible

100%

### How to reproduce

1. Flash Dasharo FW & Dasharo EC FW
2. Boot dts
3. try to flash original EC fw: `dasharo_ectool flash <path_to_ec_bin>`.

`--force` argument doesn't help

### Expected behavior

dasharo_ectool should flash binary

### Actual behavior

```
dasharo_ectool flash /NS50_70PU.04
force = false
thread 'main' panicked at src/main.rs:145:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

or

```
dasharo_ectool flash /NS50_70PU.04 --force
force = true
thread 'main' panicked at src/main.rs:145:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Screenshots

_No response_

### Additional context

Maybe flashrom could be used instead? It can at least detect EC chip.

```
flashrom -p ite_ec:boardmismatch=force
flashrom v1.2-1039-ga961af7a on Linux 6.6.21-yocto-standard (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
ITE EC programmer not (yet) supported on this device
Proceeding anyway because user forced us to.
Failed to read EC project
Failed to read EC version
Flash Part ID: 00 00 00
Found ENE flash chip "KB9012 (EDI)" (128 kB).
Found Programmer flash chip "Opaque flash chip" (128 kB, Programmer-specific) on ite_ec.
No operations were specified.
```

### Solutions you've tried

Build `dasharo_ectool` from newest https://github.com/Dasharo/ec commit, but got the same results

### PR DESCRIPTION
**Pull request by iwanicki92**
Needs to be tested on hardware, but with those changes `dasharo_ectool` should allow flashing non-Dasharo firmware.
When trying to flash vendor EC, tool should display:

```
file board: Ok("")
file version: Ok("")
```

Also fixed edge case key detection failure, where `firmware_str` wouldn't find `76EC_*` string if previous byte was also `7`.
Fixes https://github.com/Dasharo/dasharo-issues/issues/1628

### CODE REVIEW

File: tool/src/firmware.rs [hunk 1]
```diff
@@ -15,17 +15,14 @@ fn firmware_str<'a>(data: &'a [u8], key: &[u8]) -> Option<&'a [u8]> {
     while data_i < data.len() && key_i < key.len() {
         if data[data_i] == key[key_i] {
             key_i += 1;
+        } else if data[data_i] == key[0] {
```
Comment (philipanda) [inline tool/src/firmware.rs:18]: Makes sense

File: tool/src/firmware.rs [hunk 2]
```diff
@@ -15,17 +15,14 @@ fn firmware_str<'a>(data: &'a [u8], key: &[u8]) -> Option<&'a [u8]> {
...
+            key_i = 1;
         } else {
             key_i = 0;
         }
         data_i += 1;
     }
 
-    // Return None if key not found
```
Comment (philipanda) [inline tool/src/firmware.rs:24]: Why is removing this check necessary?
Without it the return type does not have to be wrapped in an `Option`

Comment (m-iwanicki) [reply tool/src/firmware.rs:24]: Commit msg: <https://github.com/Dasharo/ec/pull/77/commits/67287510523913bb76baec3e71f27c10bb3baf73>

This was my first contact with rust so I tried to make minimal changes. I also don't like to change API if it's not needed (maybe it's used somewhere I'm not aware of?)

Comment (iwanicki92) [reply tool/src/firmware.rs:24]: @philipanda Changed so firmware_str returns slice directly: 58e0c04df9ed

**Comment by philipanda** [comment]
Tested on V560TNE on DCU v2.7.2, tool built from `05effdb3d646421ce34110374d84f19127982ee6`.
`./dasharo_ectool_iwans_vendor_ec_fix flash ec_extracted_v560tnx.rom --force`
It won't flash without `--force` as expected.
I didnt' catch all the output, but the flashing has succeeded. The laptop boots. Dasharo SOL reports proprietary EC firmware.

Seems like everything is working fine in the case of V560TNE and its stock EC firmware

**Review by philipanda — APPROVED** [review]
Despite not detecting precise EC firmware size it's a very useful change.

File: tool/src/main.rs [hunk 3]
```diff
@@ -156,6 +161,7 @@ unsafe fn flash(ec: &mut Ec<Box<dyn Access>>, path: &str, target: SpiTarget, for
         println!("ec board: {:?}", str::from_utf8(ec_board));
 
         assert!(force || ec_board == firmware.board, "file board does not match ec board");
+        assert!(force || firmware.data.len() <= (128 * 1024), "ec binary size is greater than 128 kB");
```
Comment (mkopec) [inline tool/src/main.rs:164]: Meteor Lake laptops have 256kB EC flash

Comment (m-iwanicki) [reply tool/src/main.rs:164]: ROM size was hardcoded to be `let rom_size = 128 * 1024;` anyway, if you passed bigger binary only first 128 KB was flashed.

Comment (mkopec) [reply tool/src/main.rs:164]: Alright, maybe let's fix that issue in a separate PR, I'll try to handle this. Meanwhile I think this PR is good to merge.

**Review by mkopec — APPROVED** [review]
